# Generated by Django 4.1.2 on 2022-11-02 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dir', models.CharField(max_length=150)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Direction', to='edu_web.curator')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('num_groups', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Разрешены только буквенно-цифровые символы')])),
                ('max_number_students', models.IntegerField(default=20, help_text='Количество студентов в группе не может быть меньше 1-го и больше 20-ти', validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups', to='edu_web.curator')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='None', max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='edu_web.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dis', models.CharField(max_length=150)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Discipline', to='edu_web.direction')),
            ],
        ),
    ]
