# Generated by Django 4.1.2 on 2022-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='group',
            field=models.ManyToManyField(related_name='group_discipline', to='edu_web.groups', verbose_name='Изучаемая дисциплина'),
        ),
    ]
