# Generated by Django 4.1.2 on 2022-11-03 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='curator',
            name='phone_number',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате «+7------». Допускается до 15 цифр', regex='^\\+?7?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
