# Generated by Django 4.1.3 on 2022-11-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['first_name']},
        ),
    ]
