# Generated by Django 4.1.2 on 2022-11-04 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0002_curator_mail_address_curator_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='num_students',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curator',
            name='phone_number',
            field=models.CharField(help_text='Формат ввода номера +7', max_length=16, validators=[django.core.validators.RegexValidator('^\\+?7?\\d{9,15}$', 'Номер телефона необходимо вводить в формате «+7------». Допускается до 15 цифр')]),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name_dir',
            field=models.CharField(max_length=150, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group', to='edu_web.curator'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='None', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='edu_web.groups'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
