# Generated by Django 4.1.2 on 2022-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0002_discipline_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='group',
        ),
        migrations.AddField(
            model_name='groups',
            name='disciplines',
            field=models.ManyToManyField(related_name='groups', to='edu_web.discipline', verbose_name='Изучаемые дисциплины'),
        ),
    ]
