# Generated by Django 4.1.3 on 2022-11-29 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_web', '0002_alter_students_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='permcurator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direction',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curatordirections', to='edu_web.curator'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directiondisciplines', to='edu_web.direction'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curatorgroups', to='edu_web.curator'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='disciplines',
            field=models.ManyToManyField(related_name='groupsdisciplines', to='edu_web.discipline', verbose_name='Изучаемые дисциплины'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studygroup', to='edu_web.groups'),
        ),
    ]
