# Generated by Django 4.1.3 on 2022-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0003_alter_curator_user_alter_direction_curator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='direction',
            field=models.ManyToManyField(related_name='groupsdirection', to='edu_web.direction', verbose_name='Изучаемые дисциплины'),
        ),
    ]
