# Generated by Django 4.1.2 on 2022-11-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0003_groups_num_students_alter_curator_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='num_students',
        ),
    ]
