# Generated by Django 4.1.2 on 2022-11-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0004_remove_groups_num_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group_name',
            new_name='name',
        ),
    ]
