# Generated by Django 4.1.3 on 2022-11-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_web', '0004_groups_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='direction',
        ),
        migrations.AddField(
            model_name='groups',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupsdirection', to='edu_web.direction', verbose_name='Изучаемые дисциплины'),
            preserve_default=False,
        ),
    ]
