# Generated by Django 4.1.3 on 2022-12-01 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_web', '0005_remove_groups_direction_groups_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='num_groups',
            new_name='group_number',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='disciplines',
        ),
        migrations.AlterField(
            model_name='curator',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='curatoruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groups',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='edu_web.direction', verbose_name='Изучаемые дисциплины'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='edu_web.groups'),
        ),
    ]
